---
title: "Hippo_Asymm_PC"
output: pdf_document
---

```{r}

library(readxl)
library(dplyr)
library("devtools")
library("corrplot")
library("ggplot2")
library("survival")
library("Formula")
library("lattice")
library("magrittr")
library("ggpubr")
library("plyr")
library("dplyr")
library("Matrix")
library("lme4")
library("factoextra")
library("ggfortify")
library("Hmisc")
library("tidyr")
library("lme4")
library("lmtest")
library("lmerTest")
library("emmeans")
library("car")
library("cNORM")
library("BBmisc")
library("psych")

```

```{r}
HipAPC <- read_excel("~/Desktop/R/PretermControl/asymmetry/Hippo_Asymmetry_Reduced.xlsx")
str(HipAPC)

HipAPC$Group <- as.factor(HipAPC$Group)

HipAPC$Gender <- as.factor(HipAPC$Gender)

HipAPC$Age <- as.numeric(HipAPC$Age)

HipAPC$Status <- as.factor(HipAPC$Status)

HipAPC$GA <- as.numeric(HipAPC$GA)

HipAPC$Pds_N <- as.numeric(HipAPC$Pds_N)

str(HipAPC)

#check the data for outliers
summary(HipAPC)

levels(HipAPC$Group)

#relevel

HipAPC$Status <- relevel(HipAPC$Status, ref= "Preterm")

```

```{r}

#some overall summaries

library(arsenal)

#writecsv with this table

#Again with Volumetrically Corrected Data


table_one <- tableby(Group ~ ., data= HipAPC)
tab2 <- summary(table_one, title= "test", text= TRUE, results= "asis")

tab2

write.csv(tab2, "~/Desktop/HipAPCSummary.csv")

res.aov <- HipAPC %>% anova_test(fimbria ~ ICV + Status)
get_anova_table(res.aov)


```

To Volumetrically Correct the Data

for (column.name in names(HipAPC) [9:ncol(HipAPC)]) {
  HipAPC[column.name] = HipAPC[column.name] / HipAPC$ICV
}

view(HipAPC)

```{r}

#means 

means <- HipAPC %>%
  group_by(Status) %>%
  summarise_if(is.numeric, mean)

trymean <- as.data.frame(t(means), stringsAsFactors = FALSE)
trymean

write.csv(trymean, "~/Desktop/PVAL/filtered/ThalPCmeans.csv")

filmean <- trymean[-c(1:2), ]

colnames(filmean) <- c("Mean_Preterm", "Mean_Control")

sd <- HipAPC %>%
  group_by(Status) %>%
  summarise_if(is.numeric, SD)

sd
trsd <- as.data.frame(t(sd), stringsAsFactors = FALSE)
trsd

write.csv(trsd, "~/Desktop/PVAL/filtered/HipAsymPCSD.csv")

filsd <- trsd[-c(1:3), ]

colnames(filsd) <- c("SD_Preterm", "SD_Control")

filsd$SD_Post <- as.numeric(filsd$SD_Preterm)


filmean$Mean_Preterm <- paste(filmean$Mean_Preterm, filsd$SD_Preterm, sep=" ±")

filmean$Mean_Control <- paste(filmean$Mean_Control, filsd$SD_Control, sep=" ±")

filmean

colnames(filmean) <- c("Mean ± SD Preterm", "Mean ± SD Control")

filmean

write.csv(filmean, "~/Desktop/PVAL/filtered/ThalMeansSD.csv")




```

```{r}

#testing lmer
library(lme4)

l1 <- lm(data= HipAPC, Whole_hippocampus ~ Status + Age)

summary(l1)

#looping lm for entire data set

storage <- list()
for(i in names(HipAPC)[-c(1:8)]){
  storage[[i]] <- lm(get(i) ~ Status, HipAPC)
}


library(dplyr)
library(tidyr)
library(tidyverse)
library(devtools)


table <-  storage %>% tibble(
    dvsub = names(.),
    untidied = .
    ) %>%
  mutate(tidy = map(untidied, broom::tidy)) %>%
  unnest(tidy) 

tab <- as.data.frame(table)

to <- subset(tab, select = -c(2))

newtable <- filter(to, term == "StatusPreterm")

newtable

write.csv(to, "~/Documents/HipAPCpvalues.csv")

head(newtable)

pvaluec <- subset(newtable, p.value < 0.05)

pvaluec

```
Hip <-as.data.frame(HipAPC[,c(9:28)])
dim(Hip)
for (i in 9:length(Hip)) { 
  variable <- Hip[,i]
  lme_cer <- lmer(variable ~ Group + ICV + (1 | Subject), data = HipAPC, REML = FALSE)
print(summary(lme_cer))
}

```{r}

#effect sizes 

#effect sizes

library(effectsize)


stor <- list()
stor2 <- list()
for(i in names(HipAPC)[-c(1:8)]) {
 stor[[i]] <- lm(as.formula(paste(i, "~ Status")), 
    data = HipAPC)
 stor2[[i]] <- effectsize(stor[[i]])
}

stor3 <- as.data.frame(stor2)



es <- as.data.frame(t(stor3), stringsAsFactors = FALSE)



colnames(es) <- c("Intercept", "Effect_Size(Confidence_Intervals)")

head(es)

write.csv(es, "~/Desktop/PVAL/ordered/HipAsymEffectSizes.csv")

newtable <- cbind(filmean, newtable)

newtable


```

```{r}


ordered <- newtable[order(newtable$p.value), ]

head(ordered)

write.csv(ordered, "~/Documents/HipAPCorderedpvalues.csv")

pvals <- ordered$p.value

FDR = p.adjust(pvals, "fdr")
res2 = cbind(pvals, FDR=round(FDR, 3))

res2

write.csv(res2, "~/Documents/correctionsHippoPC.csv")

final <- cbind(ordered, FDR=round(FDR, 3))

final

write.csv(final, "~/Desktop/PVAL/final/finalhippoPCt.csv")


```

NONE

```{r}
#testing other associations


storage2 <- list()
for(i in names(HipAPC)[-c(1:9)]){
  storage2[[i]] <- lm(get(i) ~ Status, HipAPC)
}


library(dplyr)
library(tidyr)
library(tidyverse)
library(devtools)


table2 <-  storage2 %>% tibble(
    dvsub = names(.),
    untidied = .
    ) %>%
  mutate(tidy = map(untidied, broom::tidy)) %>%
  unnest(tidy) 

tab <- as.data.frame(table2)

to <- subset(tab, select = -c(2))

head(to) 

newtable <- filter(to, term == "StatusControl")

newtable

write.csv(to, "~/Documents/HipAPCpvalues.csv")

head(newtable)

pvaluec <- subset(newtable, p.value < 0.05)

pvaluec
```

```{r}


library(emmeans)
library(rstatix)

ThalPC3 <- read_excel("~/Desktop/R/PretermControl/asymmetry//Hippo_Asymmetry_Reduced.xlsx")

ThalPC3

responseList <- names(ThalPC3)[-c(1:8)]

pwc1 <- list()
for (i in responseList) 
  pwc1[[i]] <- ThalPC3 %>% 
  emmeans_test(as.formula(paste(i, "~ Status")),
    p.adjust.method = "fdr")


ph <-data.table::rbindlist(pwc1, fill = T)

ph
means <- HipAPC %>%
  group_by(Status) %>%
  summarise_if(is.numeric, mean)

trymean <- as.data.frame(t(means), stringsAsFactors = FALSE)
trymean

write.csv(trymean, "~/Desktop/PVAL/filtered/ThalPCmeans.csv")

filmean <- trymean[-c(1:2), ]

colnames(filmean) <- c("Mean_Preterm", "Mean_Control")

sd <- HipAPC %>%
  group_by(Status) %>%
  summarise_if(is.numeric, SD)

sd
trsd <- as.data.frame(t(sd), stringsAsFactors = FALSE)
trsd

write.csv(trsd, "~/Desktop/PVAL/filtered/HipAsymPCSD.csv")

filsd <- trsd[-c(1:3), ]

colnames(filsd) <- c("SD_Preterm", "SD_Control")

filsd$SD_Post <- as.numeric(filsd$SD_Preterm)


filmean$Mean_Preterm <- paste(filmean$Mean_Preterm, filsd$SD_Preterm, sep=" ±")

filmean$Mean_Control <- paste(filmean$Mean_Control, filsd$SD_Control, sep=" ±")

filmean

colnames(filmean) <- c("Mean ± SD Preterm", "Mean ± SD Control")

filmean

write.csv(filmean, "~/Desktop/PVAL/filtered/ThalMeansSD.csv")


#lets just try

library(effectsize)


stor <- list()
stor2 <- list()
for(i in names(ThalPC3)[-c(1:8)]) {
 stor[[i]] <- aov(as.formula(paste(i, "~ Status")), covariate= "ICV", data= ThalPC3) 
 stor2[[i]] <- effectsize(stor[[i]])
}

ees <-data.table::rbindlist(stor2, fill = T)

ees

phh <- cbind(filmean, ph, ees)

phh

##


ordered <-phh[order(phh$p), ]

head(ordered)

write.csv(ordered, "~/Desktop/PVAL/ordered/ThalPC3orderedpvalues.csv")

pvals <- ordered$p
pvals

FDR = p.adjust(pvals, "fdr")
res2 = cbind(pvals, FDR=round(FDR, 3))

res2

write.csv(res2, "~/Desktop/PVAL/fdr/correctionsThalpoPC.csv")

final <- cbind(ordered, FDR=round(FDR, 3))

final

write.csv(final, "~/Desktop/PVAL/final/hippoASymFINAL.csv")


```


