---
title: "HipAsypo_Asymmetry_PC"
output: pdf_document
---


```{r}

library(readxl)
library(dplyr)
library("devtools")
library("corrplot")
library("ggplot2")
library("survival")
library("Formula")
library("lattice")
library("magrittr")
library("ggpubr")
library("plyr")
library("dplyr")
library("Matrix")
library("lme4")
library("factoextra")
library("ggfortify")
library("Hmisc")
library("tidyr")
library("lme4")
library("lmtest")
library("lmerTest")
library("emmeans")
library("car")
library("cNORM")
library("BBmisc")
library("psych")

```

```{r}
HipAsyPC <- read_excel("Desktop/R/PretermControl/asymmetry/Hippo_Asymmetry_Reduced.xlsx")

str(HipAsyPC)

HipAsyPC$Group <- as.factor(HipAsyPC$Group)

HipAsyPC$Gender <- as.factor(HipAsyPC$Gender)

HipAsyPC$Age <- as.numeric(HipAsyPC$Age)

HipAsyPC$Status <- as.factor(HipAsyPC$Status)

HipAsyPC$GA <- as.numeric(HipAsyPC$GA)

HipAsyPC$Pds_N <- as.numeric(HipAsyPC$Pds_N)

str(HipAsyPC)

#check the data for outliers
summary(HipAsyPC)

levels(HipAsyPC$Group)

#relevel

HipAsyPC$Status <- relevel(HipAsyPC$Status, ref= "Preterm")

```

```{r}

#some overall summaries

library(arsenal)

#writecsv with this table

#Again with Volumetrically Corrected Data


table_one <- tableby(Group ~ ., data= HipAsyPC)
tab2 <- summary(table_one, title= "test", text= TRUE, results= "asis")

tab2

write.csv(tab2, "~/Desktop/HipAsyPCSummary.csv")



```

To Volumetrically Correct the Data

for (column.name in names(HipAsyPC) [9:ncol(HipAsyPC)]) {
  HipAsyPC[column.name] = HipAsyPC[column.name] / HipAsyPC$ICV
}

view(HipAsyPC)


```{r}

#testing lmer
library(lme4)

l1 <- lm(data= HipAsyPC, left_Whole_hippocampus ~ Status + Age)

summary(l1)
```

```{r}


#looping lm for entire data set

storage <- list()
for(i in names(HipAsyPC)[-c(1:9)]){
  storage[[i]] <- lm(get(i) ~ Status, HipAsyPC)
}


library(dplyr)
library(tidyr)
library(tidyverse)
library(devtools)


table <-  storage %>% tibble(
    dvsub = names(.),
    untidied = .
    ) %>%
  mutate(tidy = map(untidied, broom::tidy)) %>%
  unnest(tidy) 

tab <- as.data.frame(table)

to <- subset(tab, select = -c(2))

newtable <- filter(to, term == "StatusControl")

newtable

write.csv(to, "~/Documents/HipAsyPCpvalues.csv")

head(newtable)

pvaluec <- subset(newtable, p.value < 0.05)

pvaluec

```
HipAsy <-as.data.frame(HipAsyPC[,c(9:28)])
dim(HipAsy)
for (i in 9:length(HipAsy)) { 
  variable <- HipAsy[,i]
  lme_cer <- lmer(variable ~ Group + ICV + (1 | Subject), data = HipAsyPC, REML = FALSE)
print(summary(lme_cer))
}
```{r}


ordered <- newtable[order(newtable$p.value), ]

head(ordered)

write.csv(ordered, "~/Documents/HipAsyPCorderedpvalues.csv")

pvals <- ordered$p.value

FDR = p.adjust(pvals, "fdr")
res2 = cbind(pvals, FDR=round(FDR, 3))

res2

write.csv(res2, "~/Documents/correctionsHipAsypoPC.csv")

final <- cbind(ordered, FDR=round(FDR, 3))

final

write.csv(final, "~/Documents/finalHipAsypoPCt.csv")


```

